testing the latest tag

diff --git a/.github/workflows/test_relatedness.yml b/.github/workflows/test_relatedness.yml
--- a/.github/workflows/test_relatedness.yml
+++ b/.github/workflows/test_relatedness.yml
@@ -55,5 +55,16 @@ jobs:
 
           head cecret/iqtree2/iqtree2.treefile
 
+      - name: Run Cecret with latest
+        run: |
+          nextflow run . -profile docker,latest -c .github/workflows/github_actions.config --relatedness true --fastas fastas --outdir cecret2 -resume || echo "Failed!"
+
+          ls cecret*
+            
+          head cecret*/cecret_results.txt
+
+          head cecret*/iqtree2/iqtree2.treefile
+
+
       - name: Clean
         run: rm -rf work .nextflow*
